"""initial schema

Revision ID: 0c1ee9f87b1c
Revises: 
Create Date: 2026-09-06 23:20:15.512498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1ee9f87b1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('trips',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('origin_name', sa.String(length=200), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lng', sa.Float(), nullable=True),
    sa.Column('destination_name', sa.String(length=200), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('num_travelers', sa.Integer(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('trip_style', sa.String(length=50), nullable=False),
    sa.Column('constraints', sa.String(length=2000), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_owner_id'), ['owner_id'], unique=False)

    op.create_table('accommodations',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('price_per_night', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodations_trip_id'), ['trip_id'], unique=False)

    op.create_table('budget_items',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source_ref', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_items_trip_id'), ['trip_id'], unique=False)

    op.create_table('contingencies',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('plan_level', sa.String(length=2), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('condition', sa.String(length=300), nullable=False),
    sa.Column('affected_activity_ids', sa.JSON(), nullable=False),
    sa.Column('fallback_plan', sa.JSON(), nullable=False),
    sa.Column('budget_impact', sa.Float(), nullable=True),
    sa.Column('time_impact_minutes', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('requires_user_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contingencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contingencies_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contingencies_trigger'), ['trigger'], unique=False)
        batch_op.create_index(batch_op.f('ix_contingencies_trip_id'), ['trip_id'], unique=False)

    op.create_table('copilot_messages',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_messages_trip_id'), ['trip_id'], unique=False)

    op.create_table('itinerary_days',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_days_trip_id'), ['trip_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('weather_suitability', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('data_source', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_trip_id'), ['trip_id'], unique=False)

    op.create_table('transport_options',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('origin_name', sa.String(length=200), nullable=False),
    sa.Column('destination_name', sa.String(length=200), nullable=False),
    sa.Column('departure_at', sa.String(length=40), nullable=False),
    sa.Column('arrival_at', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_options_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_events',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_events_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_preferences',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('person_name', sa.String(length=120), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_preferences_trip_id'), ['trip_id'], unique=False)

    op.create_table('weather_snapshots',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('fetched_at', sa.String(length=40), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_snapshots_trip_id'), ['trip_id'], unique=False)

    op.create_table('activities',
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('day_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('weather_sensitive', sa.Boolean(), nullable=False),
    sa.Column('indoor', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('user_selected', sa.Boolean(), nullable=False),
    sa.Column('ai_recommended', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['itinerary_days.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_day_id'), ['day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_trip_id'))
        batch_op.drop_index(batch_op.f('ix_activities_day_id'))

    op.drop_table('activities')
    with op.batch_alter_table('weather_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_snapshots_trip_id'))

    op.drop_table('weather_snapshots')
    with op.batch_alter_table('trip_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_preferences_trip_id'))

    op.drop_table('trip_preferences')
    with op.batch_alter_table('trip_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_events_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_events_kind'))

    op.drop_table('trip_events')
    with op.batch_alter_table('transport_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_options_trip_id'))

    op.drop_table('transport_options')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_trip_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_status'))

    op.drop_table('recommendations')
    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_days_trip_id'))

    op.drop_table('itinerary_days')
    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_messages_trip_id'))

    op.drop_table('copilot_messages')
    with op.batch_alter_table('contingencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contingencies_trip_id'))
        batch_op.drop_index(batch_op.f('ix_contingencies_trigger'))
        batch_op.drop_index(batch_op.f('ix_contingencies_status'))

    op.drop_table('contingencies')
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_items_trip_id'))
        batch_op.drop_index(batch_op.f('ix_budget_items_category'))

    op.drop_table('budget_items')
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodations_trip_id'))

    op.drop_table('accommodations')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_owner_id'))

    op.drop_table('trips')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
